site_name: My Sample API Documentation
site_description: This is sample documentation for reservation API
site_url: https://veeranpatil-boop.github.io/my-sample-api-doc/
site_author: Veeran Patil

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch

nav:
  - Home: README.md
  - Getting Started: getting-started.md
  - Authentication: authentication.md
  - Errors: errors.md
  - Pagination: pagination.md
  - rate-limiting: rate-limiting.md
  - Webhooks : webhooks.md